---
apiVersion: servicecatalog.k8s.io/v1beta1
kind: ServiceBinding
metadata:
  name: bind5
  namespace: "${INSTANCE_NAMESPACE}"
spec:
  instanceRef:
    name: "${INSTANCE_NAME}"
  secretTransforms:
  - addKey:
      key: "my-new-key"
      jsonPathExpression: "${EXPRESSION}"
