apiVersion: operators.coreos.com/v1alpha1
kind: CatalogSource
metadata:  
  labels:
    csc-owner-name: installed-redhat-openshift-operators
    csc-owner-namespace: openshift-marketplace
  name: installed-redhat-openshift-operators
  namespace: openshift-operators
spec:
  address: 172.30.31.33:50051
  displayName: Red Hat Operators
  icon:
    base64data: ""
    mediatype: ""
  publisher: Red Hat
  sourceType: grpc
